services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
    - ./nginx:/etc/nginx/templates
    environment:
    - NGINX_HOST= ${NGINX_HOST}
    ports:
    - "8080:443"
    networks:
      - webnet

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always  
    volumes:
      - ./server/srcs:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      API42_DEV: true
      API42_UID: ${API42_UID}
      API42_SECRET: ${API42_SECRET}
      API42_REDIRECT_URI: ${API42_REDIRECT_URI}
      API_MASTER_KEY: ${API_MASTER_KEY}
      MONGO_URL: ${MONGO_URL}
      MONGO_DATABASE: ${MONGO_DATABASE}
    networks:
      - webnet
  
  bot:
    container_name: bot
    build:
      context: ./discord-bot
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./discord-bot/srcs:/app
      - /app/node_modules
    environment:
      API42_UID: ${API42_UID}
      API42_SECRET: ${API42_SECRET}
      API42_REDIRECT_URI: ${API42_REDIRECT_URI}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MONGO_URL: ${MONGO_URL}
      MONGO_DATABASE: ${MONGO_DATABASE}
      API_MASTER_KEY: ${API_MASTER_KEY}
    networks:
        - webnet

  mongo:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - webnet

volumes:
  database:

networks:
  webnet:
    driver: bridge