services:
  server:
    build:
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./srcs:/app
      - ./node_modules:/app/node_modules
      - /home/ibertran/projects/42exam-tracker/node_modules/@ibertran/api42:/app/node_modules/@ibertran/api42
    environment:
      API42_UID: ${API42_UID}
      API42_SECRET: ${API42_SECRET}
      MONGO_URI: ${MONGO_URI}
      API42_DEV: true

  mongo:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: projects-tracker

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
      ME_CONFIG_BASICAUTH: false

volumes:
  database: