services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 4000:4000
    environment:
      API42_UID: ${API42_UID}
      API42_SECRET: ${API42_SECRET}
      MONGO_URL: ${MONGO_URL}
      MONGO_DATABASE: ${MONGO_DATABASE}

  mongo:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_WEB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_WEB_PASSWORD}

volumes:
  database:
  redis:
